Refactor gpu
DefiosLab/Raspi4GPGPU_guide pull request #5
Opened 2023-11-02 20:22 UTC by Taiki-azrs

chap06のGPGPU実装関連を修正しました。
主に行列積の高速化、端数対応、ViTの実行ライブラリの修正です。

2023-11-08 06:12 UTC, TakedaHiromasa approved these changes
Approveとしますが、コメントを残します。

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
>          # shl(r0,r0,4)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
> +        # rotate(broadcast,r2,-A_STR)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
> +            # eidx(b_cur)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
> +                    # rotate(broadcast,r4,0)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
> +            # C_ref = np.zeros(C.shape)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +        # data2_shape = list(self.input_data2.shape)
不要？

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +            # shl(r0,r0,4)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +            # rotate(broadcast,r2,-A_STR)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +                # eidx(b_cur)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +                        # rotate(broadcast,r4,0)
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/runtime.py
> +        # self.model=model
不要

2023-11-08 06:12 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer_dict.py
>  #               "Softmax":Softmax,"Erf":Erf,"Gemm":Gemm}
上の行と同じに見える

2023-11-10 22:19 UTC, TakedaHiromasa commented
@Taiki-azrs   
対応するか否かおまかせします、良いと思ったところでマージお願いします。

2023-11-10 22:23 UTC, TakedaHiromasa requested changes

2023-11-10 22:23 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
> +            return p * q * r * 2 / average_gpu_time * 1e-9
すみません、ここの関数に実装が引数にtimeをとっていますが、関数内で直接 average_gpu_timeを扱っておりtimeは使用していません。
また、GFLOPS計算も CPU & GPU からGPUの数値のみ表示となっており機能が縮小されています。

2023-11-25 17:14 UTC, Taiki-azrs commented on chap06/sgemm_16x32.py
> +            return p * q * r * 2 / average_gpu_time * 1e-9
修正しました

2023-11-25 17:19 UTC, Taiki-azrs commented
不要なコメント全般削除しました

2023-11-25 20:29 UTC, TakedaHiromasa commented on chap06/sgemm_16x32.py
>              # 32 x 4(float) x jidx
このコメント通りの処理が以下で行われているように読み取れないと思いましたが、もう少し下の行で ldi128 x jidx が行われているのですね
だとするとコメント位置は最適ではない気がします

2023-11-25 20:29 UTC, TakedaHiromasa commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +                # 32 x 4(float) x jidx
sgemmでのコメントと同じく

2023-11-25 20:38 UTC, Taiki-azrs commented on chap06/vit_for_vc6/layer/matmul_gpu.py
> +                # 32 x 4(float) x jidx
修正しました。

2023-11-25 20:38 UTC, Taiki-azrs commented on chap06/sgemm_16x32.py
>              # 32 x 4(float) x jidx
修正しました。

2023-11-25 20:38 UTC, Taiki-azrs commented
修正確認出来たらresolve conversionお願いします。

2023-11-25 21:09 UTC, TakedaHiromasa approved these changes
LGTM💪

2023-11-25 21:32 UTC, merged